server:
  port: 8082
  
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://10.60.150.44:3306/dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Tongji@2020
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
        
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.60.150.45:8761/eureka/
