server:
  port: 8010
  
spring:
  application:
    name: behaviour-service
  datasource:
    url: jdbc:mysql://10.60.150.44:3306/behaviour
    username: root
    password: Tongji@2020
    driver-class-name: com.mysql.jdbc.Driver
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.60.150.45:8761/eureka/
